Repository Rebilly/rebilly-js-sdk, pull requests merged in 2018-05, with the labels that each got.

#70 Update email notifications to latest Rebilly spec
  src/create-api-instance.js
  src/resources/email-notifications-resource.js
  src/resources/index.js
  src/resources/previews-resource.js
  test/unit/specs/api-instance.spec.js
Labels: feature

#71 Enable criteria for transaction histogram data
  src/resources/experimental/histograms-resource.js
Labels: enhancement

#72 Fix reset-password endpoint
  src/resources/users-resource.js
Labels: bug
