Repository Rebilly/rebilly-js-sdk, pull requests merged in 2018-11, with the labels that each got.

#98 Add the emailMessages endpoint to the JS SDK
  src/create-api-instance.js
  src/resources/email-messages-resource.js
  src/resources/index.js
  test/unit/specs/api-instance.spec.js
Labels: feature

#101 Temporarily fix deep-freeze issue with Firefox
  src/collection.js
  src/member.js
Labels: bug

#102 Fix cancelToken and deepFreeze conflict in Firefox
  src/collection.js
  src/create-api-handler.js
  src/deep-freeze.js
  src/member.js
Labels: bug

#104 Add query support to coupons resource
  docs/reference/resources/coupons.md
  src/resources/coupons-resource.js
Labels: enhancement
