Repository Rebilly/rebilly-js-sdk, pull requests merged in 2019-06, with the labels that each got.

#140 Fix disto
  .babelrc
  package.json
  webpack.config.js
  yarn.lock
Labels: bug

#141 Fix getAllOAuth2Credentials response
  package.json
  src/resources/credential-hashes-resource.js
Labels: bug

#143 Add close gateway account endpoint
  docs/reference/resources/gateway-accounts.md
  package.json
  src/resources/gateway-accounts-resource.js
Labels: feature

#144 Create resource for bank names (GWY-11871)
  docs/reference/rebilly-api.md
  docs/reference/resources/payment-cards-bank-names.md
  package.json
  src/create-api-instance.js
  src/index.js
  src/resources/index.js
  src/resources/payment-cards-bank-names-resource.js
Labels: enhancement

#145 Add Segments resource
  package.json
  src/create-api-instance.js
  src/index.js
  src/resources/index.js
  src/resources/segments-resource.js
Labels: feature
