Repository Rebilly/rebilly-js-sdk, pull requests merged in 2019-12, with the labels that each got.

#181 Add methods PUT, DELETE, GET for memberships
  docs/reference/resources/memberships.md
  package.json
  src/resources/memberships-resource.js
Labels: feature

#182 Fix bug in emailDeliverySettings resource
  package.json
  src/resources/email-delivery-settings-resource.js
Labels: bug

#183 Enable resending a verification email
  package.json
  src/resources/email-delivery-settings-resource.js
Labels: enhancement

#184 Add review endpoint for KYC documents
  docs/reference/resources/kyc-documents.md
  package.json
  src/resources/kyc-documents-resource.js
Labels: enhancement
