Repository Rebilly/rebilly-js-sdk, pull requests merged in 2019-03, with the labels that each got.

#123 Add expand param to invoices.getAllInvoiceItems
  src/resources/invoices-resource.js
Labels: enhancement

#127 Added endpoint to receive OAuth2 credentials items
  src/resources/credential-hashes-resource.js
Labels: enhancement

#129 Upgrade webpack up to v3.12
  yarn.lock
Labels: security

#130 Upgrade dev babel packages
  yarn.lock
Labels: security

#131 Fix getOAuth2CredentialItems
  src/resources/credential-hashes-resource.js
Labels: bug

#132 Allow additional params for `getOAuth2CredentialItems`
  src/resources/credential-hashes-resource.js
Labels: enhancement

#133 Added new endpoints for upcoming invoices
  src/resources/customers-resource.js
  src/resources/subscriptions-resource.js
Labels: feature
