Repository Rebilly/rebilly-js-sdk, pull requests merged in 2019-02, with the labels that each got.

#113 Add Search Endpoint
  src/create-api-instance.js
  src/resources/index.js
  src/resources/search-resource.js
Labels: enhancement

#115 Add support for expand when creating certain entities
  src/create-api-handler.js
  src/resources/checkout-pages-resource.js
  src/resources/contacts-resource.js
  src/resources/customers-resource.js
  src/resources/disputes-resource.js
  src/resources/experimental/data-exports-resource.js
  src/resources/invoices-resource.js
  src/resources/kyc-documents-resource.js
  src/resources/subscriptions-resource.js
  src/resources/transactions-resource.js
Labels: enhancement

#116 Update transaction creation to use new endpoint
  README.md
  docs/index.md
  docs/reference/resources/transactions.md
  src/resources/transactions-resource.js
Labels: enhancement

#117 tags resource: fix 'update' method
  src/resources/tags-resource.js
Labels: bug

#119 Add Invoice timeline
  docs/reference/resources/invoices.md
  src/resources/invoices-resource.js
Labels: feature

#118 Add Integrations Resource
  src/create-api-instance.js
  src/resources/index.js
  src/resources/integrations-resource.js
Labels: enhancement, feature

#121 Fix implementation of interceptor ejection in the JS SDK
  package.json
  src/create-api-handler.js
  test/unit/specs/api-handler.spec.js
Labels: bug
