Repository Rebilly/rebilly-js-sdk, pull requests merged in 2019-11, with the labels that each got.

#169 Added broadcast messages resource
  src/create-api-instance.js
  src/resources/broadcast-messages-resource.js
  src/resources/index.js
Labels: feature

#170 Release v15.3.2
  package.json
Labels: chore

#171 Changed put to patch
  package.json
  src/resources/broadcast-messages-resource.js
Labels: bug, chore

#172 Fix email delivery settings
  package.json
  src/resources/email-delivery-settings-resource.js
Labels: bug, chore

#174 Added arguments to getAll method
  package.json
  src/resources/email-delivery-settings-resource.js
Labels: bug, chore

#173 Support experimental/organizations endpoint
  docs/reference/resources/experimental/organizations.md
  package.json
  src/create-api-instance.js
  src/resources/experimental/index.js
  src/resources/experimental/organizations-resource.js
Labels: feature

#175 Support memberships endpoint
  docs/reference/resources/memberships.md
  package.json
  src/create-api-instance.js
  src/resources/index.js
  src/resources/memberships-resource.js
Labels: feature

#176 Add send through attribution end point to rebilly-js-sdk
  package.json
  src/create-api-instance.js
  src/resources/index.js
  src/resources/send-through-attribution-resource.js
Labels: feature

#177 Added event type to send-through-attribution
  src/resources/send-through-attribution-resource.js
Labels: bug

#178 Fix version and resource
  package.json
Labels: bug

#179 Update email setting verifications endpoint
  package.json
  src/resources/email-delivery-settings-resource.js
Labels: bug
